import college from "./asset/college.jpg";
export const allCollegeData = [
  {
    name: "Goenka College of Commerce and Business Administration",
    address: "Goenka College of Commerce and Business Administration",
    info: "Goenka College of Commerce and Business Administration, Kolkata, is one of the oldest and most prestigious Colleges in India. The history of the College may be traced back to 1905, when the Presidency College commercial classes developed into a separate government commercial institute, which is a front runner of the present college. The Institute was later shifted to this present site replacing the Indian Association for the Cultivation of Science. However, the present building was constructed in 1955 was christened Goenka College of Commerce and Business Administration. Since 1951, the college has been affiliated to the University of Calcutta for teaching the B. Com course. The college has from the beginning, functioned as a full-time day college for teaching the co-educational B.Com Course. Eventually, it introduced an evening section in 1965. The evening section was later on converted into Morning section. As a mark of recognition of its excellence, in 2003 the University of Calcutta has given affiliation for opening of Post Graduate course in commerce in addition to its existing B.Com (Hons) course. A significant achievement of the college was introduction of a full time Master of Business Administration (MBA) course from the academic session 2010-11. This course is affiliated to the University of Calcutta and approved by the All India Council for Technical Education (AICTE).",
    state: "WEST BENGAL",
    city: "KOLKATA",
    affiliation: "University of Calcutta",
    type: "",
    contact: "TELE - 033-2241-2216; FAX - 033-2219-2056",
    website: "www.goenkacollege.net/",
    email: "info@goenkacollege.net",
    coursesAndFees:
      "Under Graduate – B.Com. (Honours) Post Graduate – M.Com. & MBA",
    cutoff: "",
    admission:
      "GCCBA PG Admission 2020-21: M.Com 2nd Counselling Notice released. * The college conducts a strictly online application process.*For admission in B.Com (Hons.) and M.Com, the candidates must have passed a 10+2 with 75% marks and Bachelor’s degree in Commerce respectively. * The selection criterion for both UG and PG Programmes is based on Merit and availability of seats only.MBA admission requires a Bachelor’s degree in any stream with minimum 55% marks.The candidates must qualify CMAT for admission in MBA program.",
    examAccepted: "",
    facilities: [
      "Library",
      "ComputerLab",
      "e-classroom",
      "careercounselling",
      "Fellowship",
    ],
    placements: "3.6/5",
    review: "7.8/10",
    ranking: "",
    comparison: "",
    img:college
  },
  {
    name: "Jadavpur University",
    address:
      "Main Campus 188, Raja S.C. Mallick Rd, Kolkata 700032.Salt Lake Campus Plot No.8, Salt Lake Bypass, LB Block, Sector III, Salt Lake City, Kolkata 700106.",
    info: "To trace the history of Jadavpur University is to trace a part of India’s freedom movement, at least from the Swadeshi Movement onwards. It was 1905 -1906 Bengal stood divided. The times were feverish. The hegemony of the British establishment had to be challenged. Education had to play a new role in this changed scenario. It had to become a new form of resistance through which the emergent nationalist spirit could be propagated. With this in mind the National Council of Education (NCE) came into being. Its primary aim was to impart education - literary, scientific and technical on national lines exclusively under national control. To achieve self-reliance, through education. The foundation of the NCE was made possible by the munificence - scholarly as well as monetary - of the likes of Raja Subodh Chandra Mallik , Brajendra Kishore Roychowdhury of Gouripur as well as Sir Rash Behari Ghosh (first President of NCE), poet Rabindranath Tagore and Sri Aurobindo Ghosh. In 1910 the Society for the Promotion of Technical Education in Bengal which looked after Bengal Technical Institute (which later became College of Engineering and Technology, Bengal) was amalgamated to NCE. NCE henceforth looked after the College of Engineering and Technology, Bengal which by 1940 was virtually functioning as a University. After Independence, the Government of West Bengal, with the concurrence of the Govt. of India, enacted the necessary legislation to establish Jadavpur University on the 24th of December 1955. Now Jadavpur University has successfully established itself as a foremost Indian University with a vast repertoire of courses offered, an enviable list of faculty members and has come to be known for its commitment towards advanced study and research.",
    state: "WEST BENGAL",
    city: "KOLKATA",
    affiliation: "UGC Approved; NAAC Accreditation ( Grade 'A'); AIU Member",
    type: "state",
    contact: "Information Office Ph: 2457 - 2227 Main Campus Ph:+9133-24146666 Salt Lake Campus Ph: +9133-2335 5215",
    website: "www.jaduniv.edu.in",
    email: "vc@jadavpuruniversity.in registrar@jadavpuruniversity.in",
    coursesAndFees: "B.Tech - Rs.2,400 (1st Year Fees);B.Pharm - Rs.2,400 (1st Year Fees)B.Ed - Rs. 15,260 (Total Fees); B.Sc - Rs.2,400 (1st Year Fees)B.Arch - Rs.12,000 (Total Fees)BA - Rs.2,400 (1st Year Fees)B.P.Ed - Rs.2,400 (1st Year Fees) Master of Computer Applications [M.C.A]",
    cutoff: "",
    admission: "Admission to B.Pharm., B.Tech. and B.Arch. is done on the basis of WBJEE scores. Admission to ME/M.Tech. program is done on the basis of marks obtained in GATE. Candidates are shortlisted for admission to the rest of the programs on the basis of the entrance exam conducted by the University. B.Sc Admission will be granted on the basis of Merit in the qualifying examination. For B.Sc, Seats will be allotted on the basis of previous academic merit. For Ph.D Admissions, Jadavpur University also conducts entrance tests. Candidates having a valid score in CSIR NET or any other nation level Entrance exam will be exempted from Entrance test. Final Admission to Ph.D will be granted on the basis of Interview Conducted by Jadavpur UNiversity.",
    examAccepted: "",
    facilities: "• Hostel • Guest House • Library • Day Care Centre • Placement & Training • Health Centre • JU Employees' Coop Credit Society Ltd",
    placements: "3.6/5",
    review: "7.8/10",
    ranking: "",
    comparison: "",
    img:college
  },
  {
    name: "IIM Calcutta - Indian Institute of Management",
    address: "",
    info: "IIM Calcutta, the first addition to the prestigious group of IIMs in 1961, is consistently ranked #3 in NIRF Ranking for last 5 years. IIM Calcutta has carved a niche among Top Management Colleges in India. The most popular program of IIMC is MBA followed by one year MBA or Executive MBA or MBAEx. The institute is recently ranked #44 in Financial Times Global MBA Ranking 2021 for its MBAEx. Admission to 2 year MBA program is done via CAT and for MBAEx, GMAT score is considered along with a minimum work experience of 2 Years. Know more about IIM Calcutta Courses & Eligibility",
    state: "WEST BENGAL",
    city: "KOLKATA",
    affiliation: "UGC",
    type: "Public/Government",
    contact: "",
    website: "",
    email: "",
    coursesAndFees: "",
    cutoff: "",
    admission: "",
    examAccepted: "",
    facilities: "",
    placements: "",
    review: "",
    ranking: "",
    comparison: "",
    img:college
  },
  {
    name: "J.D Birla Institute (JDBI)",
    address: "",
    info: "JD Birla Institute was established in 1962 and is located in Kolkata in the state of West Bengal. The institute has completed more than 50 years and has been graded ‘A’ by the National Assessment and Accreditation Council (NAAC). The institute has ranked 10 out of 120 colleges by Nielsons for India Today in the Department of Management and ranked 31 out of 145 colleges in the Department of Commerce. J.D. Birla Institute is a private unaided college and is affiliated with Jadavpur University, Kolkata. The institute offers undergraduate courses in Science, Commerce and Management. The institute also offers courses for PG students in Science and Commerce. The institute has all the important facilities like library, computer centres, gym, cafeteria, etc. but doesn’t have a dedicated hostel for students. The institute has been awarded several prestigious awards like The Economic Times Best Education Brand Award 2020.",
    state: "WEST BENGAL",
    city: "KOLKATA",
    affiliation: "jadavpur university",
    type: "PRIVATE INSTITUTE (AUTONOMOUS)",
    contact: "",
    website: "",
    email: "",
    coursesAndFees: "",
    cutoff: "",
    admission: "",
    examAccepted: "",
    facilities: "",
    placements: "",
    review: "",
    ranking: "",
    comparison: "",
    img:college
  },
  {
    name: "National Institute of Fashion Technology, Kolkata",
    address: "",
    info: "National Institute of fashion technology is located in Kolkata and is a government college that was established in 1995 in order to introduce students to various options of employment in the field of fashion.The institution offers courses at undergraduate and postgraduate levels with specialization in fields of design, management and technology. At the UG level, it offers B.Des. and B.F.Tech. At the PG level it offers MFM. Admissions to all the courses are based on written examination. As per latest updates, NIFT Admission 2021 has started for PhD programs, apply till May 2, 2021 (11:59 PM). NIFT has also started the online process for shortlisted candidates to select interview dates for PG Admission 2021. The college is one among the many branches of NIFT’s present in pan country . The institution has maintained a good record of placements with top notch fashion firms coming in the college as recruiters. The college in itself becomes a unique place to be in because of the amazing infrastructure it provides to the students with all kinds of labs required to improve one's skills in the field of fashion. The faculty members are also well qualified and experienced in the fields that they teach. The most recent acknowledgement received by the institution is the 7th rank attributed by the organisation called Outlook in 2019.",
    state: "WEST BENGAL",
    city: "KOLKATA",
    affiliation: "AICTE",
    type: "Public/Government",
    contact: "",
    website: "",
    email: "",
    coursesAndFees: "",
    cutoff: "",
    admission: "",
    examAccepted: "",
    facilities: "",
    placements: "",
    review: "",
    ranking: "",
    comparison: "",
    img:college
  },
  {
    name: "NSHM Knowledge Campus, Kolkata",
    address: "",
    info: "NSHM Knowledge Campus NSHM Knowledge Campus, Kolkata Group of Institutions has been graded B++ by NAAC. NSHM Kolkata has ranked 1st Private Pharmaceutical College in West Bengal by NIRF 2020 and awarded the ASSOCHAM Best Education Group in the East, 2019. NSHM, Kolkata offers degree courses in the discipline of Business, Management, Computer Application, Fashion Design, Media Science, Hotel Management, Pharmaceutical Sciences, Healthcare, Hospital Management, etc. NSHM has state-of-art campuses in Kolkata and Durgapur and presently has a combined enrolment of over 5,000 students.",
    state: "WEST BENGAL",
    city: "KOLKATA",
    affiliation: "AICTE; NAAC GRADE B++",
    type: "PRIVATE",
    contact: "",
    website: "",
    email: "",
    coursesAndFees: "",
    cutoff: "",
    admission: "",
    examAccepted: "",
    facilities: "",
    placements: "",
    review: "",
    ranking: "",
    comparison: "",
    img:college
  },
  {
    name: "Nil Ratan Sircar Medical College and Hospital",
    address: "",
    info: "Dr Nilratan Sircar (1st October, 1861 - 18th May, 1943) was an eminent Indian doctor, educationist, philanthropist and swadeshi entrepreneur.NRS Medical College is the second oldest medical college in Kolkata, with us being the 144th batch of the college. The rich library, caring guiding teacher, world class infrastructure makes it one of the leading alma mater for producing doctor in the country.",
    state: "WEST BENGAL",
    city: "KOLKATA",
    affiliation: "MCI",
    type: "GOVERNMENT",
    contact: "",
    website: "",
    email: "",
    coursesAndFees: "",
    cutoff: "",
    admission: "",
    examAccepted: "",
    facilities: "",
    placements: "",
    review: "",
    ranking: "",
    comparison: "",
    img:college
  },
  {
    name: "CMI - Calcutta Media Institute",
    address: "",
    info: "Established in 2010, Calcutta Media Institute (CMI) is a wholly-owned subsidiary of ABP Pvt. Ltd. CMI is one of the leading Media Advertising and communication institutes aiming at making students industry-ready. The institute offers the postgraduate diploma, professional certificate, short-term and online courses for different duration. CMI has created and delivered courses in partnership with IISWBM, leading to a Post Graduate Diploma in Media Management (PGDMM) under Calcutta University. The Postgraduate Diploma courses come with three specialisations such as Digital Marketing & Social Media, Broadcast Management and Integrated Marketing Communications management. Student needs to select any one of the specialisation while pursuing the course CMI has collaborated with Barry O’Brien to design and deliver communication and confidence building courses for adults and children studying in middle school and high school.",
    state: "WEST BENGAL",
    city: "KOLKATA",
    affiliation: "",
    type: "PRIVATE",
    contact: "",
    website: "",
    email: "",
    coursesAndFees: "",
    cutoff: "",
    admission: "",
    examAccepted: "",
    facilities: "",
    placements: "",
    review: "",
    ranking: "",
    comparison: "",
    img:college
  },
  {
    name: "Jnan Chandra Ghosh Polytechnic College",
    address: "",
    info: "Jnan Chandra Ghosh Polytechnic was established in 1959 in Kolkata. Theinstitute is affiliated to the WBSCTE and approved by AICTE and PCI. Jnan Chandra Ghosh Polytechnic provides diploma courses in engineering and pharmacy streams across a total of 5 specializations. All the courses are full-time and admissions are done on the basis of the entrance exam for all courses. The list of students received from JEXPO for diploma in engineering and CET for diploma in pharmacy decides the admission for the candidate.",
    state: "WEST BENGAL",
    city: "KOLKATA",
    affiliation: "AICTE",
    type: "Public/Government",
    contact: "",
    website: "",
    email: "",
    coursesAndFees: "",
    cutoff: "",
    admission: "",
    examAccepted: "",
    facilities: "",
    placements: "",
    review: "",
    ranking: "",
    comparison: "",
    img:college
  },
  {
    name: "Department of Business Management - University of Calcutta",
    address: "",
    info: "Department of Business Management (BM) is a part of the University of Calcutta and was ranked at 38 as per a survey made by Business Today in 2009. The department offers MBA, MHROM, and PhD to its students. BM within a very short span of time has made its mark in the world of business by providing a high-quality management education at an affordable price. Calcutta University, Department of Business Management Admission 2021 has started for MBA (Financial Management), application forms to be received from 5 April-25 June 2021. The department is also inviting applications for admission to its MBA and MBA-HRD program for the academic year 2021. Interested and eligible candidates can apply for admission till the deadline of July 26, 2021.",
    state: "WEST BENGAL",
    city: "KOLKATA",
    affiliation: "AICTE",
    type: "Public/Government",
    contact: "",
    website: "",
    email: "",
    coursesAndFees: "",
    cutoff: "",
    admission: "",
    examAccepted: "",
    facilities: "",
    placements: "",
    review: "",
    ranking: "",
    comparison: "",
    img:college
  },
  {
    name: "Dinabandhu Andrews Institute of Technology and Management",
    address: "",
    info: "Established in 2002, Dinabandhu Andrews Institute of Technology and Management (DAITM) is one of the self-financed institute offering quality technological and management education in West Bengal. The Institute is affiliated to Maulana Abul Kalam Azad University of Technology (MAKAUT), West Bengal (formerly known as West Bengal University of Technology). DAITM is located at Baishnabghata Patuli area in Kolkata. To tune well with the educational standards, DAITM Kolkata offers three-year full-time Bachelor of Business Administration (BBA), Bachelor of Business Administration in Hospital Management (BBA-HM), Bachelor of Computer Applications (BCA) and Bachelor of Science in Medical Lab Technology (BSc MLT) degree programmes in various specialisations at UG level and MSc (Computer Science and Applied Mathematics) at PG level. DAITM provides state-of-the-art campus and infrastructure for its students to keep pace with the advanced technological environment. Apart from the high-tech classrooms and seminar rooms, the college has well-equipped computer labs and a library to cater the demand of the curriculum. Several other facilities like modern management labs, comprehensive resources, paying guest assistance for outstation students, Wi-Fi facility and 100% placement assistance make DAITM better than other institutes of Kolkata.",
    state: "WEST BENGAL",
    city: "KOLKATA",
    affiliation: "AICTE",
    type: "PRIVATE",
    contact: "",
    website: "",
    email: "",
    coursesAndFees: "",
    cutoff: "",
    admission: "",
    examAccepted: "",
    facilities: "",
    placements: "",
    review: "",
    ranking: "",
    comparison: "",
    img:college
  },
  {
    name: "Praxis Business School",
    address: "",
    info: "A premier B-School for Post-Graduate Diploma in Management (PGDM), located on the Southern outskirts of Kolkata, Praxis Business School was established in 2007. The institute is approved by All India Council for Technical Education (AICTE). Praxis Business School offers two-year, full-time PGDM course in Finance, Marketing, HR, Systems and Operations, and Post-Graduate Programme (PGP) in Data Science and Cyber Security for nine months.",
    state: "WEST BENGAL",
    city: "KOLKATA",
    affiliation: "AICTE",
    type: "Private",
    contact: "",
    website: "",
    email: "",
    coursesAndFees: "",
    cutoff: "",
    admission: "",
    examAccepted: "",
    facilities: "",
    placements: "",
    review: "",
    ranking: "",
    comparison: "",
    img:college
  },
  {
    name: "Distance Academy",
    address: "",
    info: "Popular Exams, Colleges, Courses & Specializations are identified using the student visits on Shiksha in the last 12 months. Scoring is on a relative scale from 0 to 100, where 100 signifies most visits on the respective colleges, courses or exams and 50 signifies half as many visits.",
    state: "WEST BENGAL",
    city: "KOLKATA",
    affiliation: "Private",
    type: "",
    contact: "",
    website: "",
    email: "",
    coursesAndFees: "",
    cutoff: "",
    admission: "",
    examAccepted: "",
    facilities: "",
    placements: "",
    review: "",
    ranking: "",
    comparison: "",
    img:college
  },
  {
    name: "Globsyn Business School",
    address: "",
    info: "Globsyn Business School (GBS) is recognized as India’s First Corporate B-School located in Kolkata. Globsyn Business School (GBS) boasts 100% placements since its inception. With over 360+ corporate relations, in the last academic year, over 80 national and international corporations like Amazon, Nestle India, PwC, Parle, TCS, ITC Ltd., etc. More than 300 recruiters regularly visit the institute for campus recruitment. GBS Kolkata offers courses at the post-graduate level.",
    state: "WEST BENGAL",
    city: "KOLKATA",
    affiliation: "AICTE, AACSB",
    type: "PRIVATE",
    contact: "",
    website: "",
    email: "",
    coursesAndFees: "",
    cutoff: "",
    admission: "",
    examAccepted: "",
    facilities: "",
    placements: "",
    review: "",
    ranking: "",
    comparison: "",
    img:college
  },
  {
    name: "",
    address: "",
    info: "",
    state: "",
    city: "",
    affiliation: "",
    type: "",
    contact: "",
    website: "",
    email: "",
    coursesAndFees: "",
    cutoff: "",
    admission: "",
    examAccepted: "",
    facilities: "",
    placements: "",
    review: "",
    ranking: "",
    comparison: "",
    img:college
  }
];
